// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;
using AUTD3Sharp.Link;
using System.Runtime.CompilerServices;


[assembly: InternalsVisibleTo("tests")]
namespace AUTD3Sharp.NativeMethods
{
    internal static unsafe partial class NativeMethodsAutd3CapiLinkEtherCrab
    {
        const string __DllName = "autd3_capi_link_ethercrab";





        [DllImport(__DllName, EntryPoint = "AUTDLinkEtherCrab", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ResultLink AUTDLinkEtherCrab(ConstPtr err_handler, ConstPtr err_context, EtherCrabOption option);

        [DllImport(__DllName, EntryPoint = "AUTDLinkEtherCrabIsDefault", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool AUTDLinkEtherCrabIsDefault(EtherCrabOption option);

        [DllImport(__DllName, EntryPoint = "AUTDLinkEtherCrabStatusGetMsg", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint AUTDLinkEtherCrabStatusGetMsg(Status src, byte* dst);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct EtherCrabOption
    {
        public byte* ifname;
        public Duration dc_configuration_sync0_period;
        public Duration state_check_period;
        public Duration sync_tolerance;
        public Duration sync_timeout;
    }



}
