// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;
using AUTD3Sharp.Link;
using System.Runtime.CompilerServices;


[assembly: InternalsVisibleTo("tests")]
namespace AUTD3Sharp.NativeMethods
{
    internal static unsafe partial class NativeMethodsAutd3LinkEtherCrab
    {
        const string __DllName = "autd3_link_ethercrab";

        internal const nuint MAX_SUBDEVICES = 32;
        internal const nuint MAX_FRAMES = 16;





    }


    /// <summary>
    ///  The status of the EtherCAT device.
    /// </summary>
    internal enum Status : byte
    {
        /// <summary>
        ///  The device is in SAFE-OP + ERROR.
        /// </summary>
        Error = 0,
        /// <summary>
        ///  The device is lost.
        /// </summary>
        Lost = 1,
        /// <summary>
        ///  The device is in SAFE-OP.
        /// </summary>
        StateChanged = 2,
        /// <summary>
        ///  All devices resumed OP.
        /// </summary>
        Resumed = 4,
    }


}
